# See https://github.com/kccricket/clicksort
enable_metrics: true
check_for_updates: true
debug_level: 'OFF'
drop_excess: true
default_group_name: '000-default'
ignore_plugin_inventory: false
defaults:
  enabled: true
  click_mode: SWAP
  sort_mode: NAME
  start_corner: TOP_LEFT
  fill_axis: HORIZONTAL
  sort_over_items: false
  bundle_in_inventory: false
  bundle_in_containers: false
  bundle_stack_limit: 12
locked_slots:
  player: []
action_cooldown_ms: 150
sortable_inventories:
  - "PLAYER"
  - "CHEST"
  - "CHEST_MINECART"
  - "ENDER_CHEST"
  - "SHULKER_BOX"
  - "BARREL"
  - "HOPPER"
  - "HOPPER_MINECART"
  - "DROPPER"
  - "DISPENSER"
blacklist:
  materials: []
  names: []
