name: ClickSorted
main: net.kccricket.clicksorted.ClickSortedPlugin
authors: [ desht, chengzi, kccricket ]
version: ${project.version}
description: Super-convenient inventory sorting
website: https://dev.bukkit.org/projects/clicksort
api-version: 1.20.6

permissions:
  clicksorted.admin:
    description: Full admin control for ClickSorted
    default: op
    children:
      clicksorted.commands.reload: true
      clicksorted.commands.sort: true
      clicksorted.commands.click: true
      clicksorted.commands.shiftclick: true
      clicksorted.commands.getcfg: true
      clicksorted.commands.debug: true
  clicksorted.commands.reload:
    description: Allow use of the /clicksorted reload command
    default: op
  clicksorted.commands.getcfg:
    description: Allow use of the /clicksorted getcfg command
    default: op
  clicksorted.commands.debug:
    description: Allow use of the /clicksorted debug command
    default: op
  clicksorted.commands.sort:
    description: Allow use of the /clicksorted sort command
    default: true
  clicksorted.commands.click:
    description: Allow use of the /clicksorted click command
    default: true
  clicksorted.commands.shiftclick:
    description: Allow use of the /clicksorted shiftclick command
    default: true
  clicksorted.sort:
    description: Allow all kinds of inventories to be click-sorted
    default: true
    children:
      clicksorted.sort.hotbar: true
      clicksorted.sort.player: true
      clicksorted.sort.container: true
  clicksorted.sort.hotbar:
    description: Allow hotbar to be click-sorted
    default: true
  clicksorted.sort.player:
    description: Allow player inventory (excluding hotbar) to be click-sorted
    default: true
  clicksorted.sort.container:
    description: Allow container to be click-sorted
    default: true
